IF(NOT DEFINED WORKING_DIRECTORY OR NOT DEFINED PATCH_FILE)
	MESSAGE(FATAL_ERROR "WORKING_DIRECTORY and PATCH_FILE are required")
ENDIF()

EXECUTE_PROCESS(
	COMMAND git apply --reverse --check ${PATCH_FILE}
	WORKING_DIRECTORY ${WORKING_DIRECTORY}
	RESULT_VARIABLE PATCH_ALREADY_APPLIED
	OUTPUT_QUIET
	ERROR_QUIET
)

IF(NOT PATCH_ALREADY_APPLIED EQUAL 0)
	EXECUTE_PROCESS(
 	   	COMMAND git checkout -f Cargo.lock
  	  	WORKING_DIRECTORY ${WORKING_DIRECTORY}
    	RESULT_VARIABLE CHECKOUT_RESULT
    	OUTPUT_QUIET
    	ERROR_QUIET
	)

	EXECUTE_PROCESS(
		COMMAND git apply --check ${PATCH_FILE}
		WORKING_DIRECTORY ${WORKING_DIRECTORY}
		RESULT_VARIABLE PATCH_CAN_APPLY
		OUTPUT_QUIET
		ERROR_VARIABLE PATCH_ERROR
	)
	IF(NOT PATCH_CAN_APPLY EQUAL 0)
		MESSAGE(FATAL_ERROR "Cannot apply ${PATCH_FILE}: ${PATCH_ERROR}")
	ENDIF()
	EXECUTE_PROCESS(
		COMMAND git apply ${PATCH_FILE}
		WORKING_DIRECTORY ${WORKING_DIRECTORY}
		RESULT_VARIABLE PATCH_APPLY_RESULT
	)
	IF(NOT PATCH_APPLY_RESULT EQUAL 0)
		MESSAGE(FATAL_ERROR "Failed to apply ${PATCH_FILE}")
	ENDIF()
ENDIF()
