include(ExternalProject)

function(ExternalDependency NAME)
	cmake_parse_arguments(DEP "" "GIT_REPOSITORY;GIT_TAG;TARGET;INCLUDE_DIR;LIBRARY" "CMAKE_ARGS" ${ARGN})
	string(TOUPPER "${NAME}" DEP_VAR)
	string(TOLOWER "${NAME}" DEP_NAME)

	if(NOT DEP_TARGET)
		set(DEP_TARGET "${NAME}::${DEP_NAME}")
	endif()
	if(NOT DEP_INCLUDE_DIR)
		set(DEP_INCLUDE_DIR "include")
	endif()
	if(NOT DEP_LIBRARY)
		set(DEP_LIBRARY "lib/${CMAKE_STATIC_LIBRARY_PREFIX}${DEP_NAME}${CMAKE_STATIC_LIBRARY_SUFFIX}")
	endif()

	set(DEP_PREFIX "${CMAKE_BINARY_DIR}/_deps/${DEP_NAME}")
	set(DEP_INSTALL_DIR "${DEP_PREFIX}/install")
	set(DEP_INCLUDE_PATH "${DEP_INSTALL_DIR}/${DEP_INCLUDE_DIR}")
	set(DEP_LIBRARY_PATH "${DEP_INSTALL_DIR}/${DEP_LIBRARY}")
	set(DEP_CMAKE_ARGS
		-DCMAKE_INSTALL_PREFIX=${DEP_INSTALL_DIR}
		-DCMAKE_POSITION_INDEPENDENT_CODE=ON
		-DBUILD_SHARED_LIBS=OFF
		${DEP_CMAKE_ARGS}
	)
	file(MAKE_DIRECTORY "${DEP_INCLUDE_PATH}")

	if(CMAKE_TOOLCHAIN_FILE)
		list(APPEND DEP_CMAKE_ARGS -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE})
	endif()
	if(CMAKE_CROSSCOMPILING_EMULATOR)
		list(APPEND DEP_CMAKE_ARGS -DCMAKE_CROSSCOMPILING_EMULATOR=${CMAKE_CROSSCOMPILING_EMULATOR})
	endif()
	if(CMAKE_BUILD_TYPE)
		list(APPEND DEP_CMAKE_ARGS -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE})
	endif()

	ExternalProject_Add(${DEP_NAME}_external
		PREFIX "${DEP_PREFIX}"
		GIT_REPOSITORY "${DEP_GIT_REPOSITORY}"
		GIT_TAG "${DEP_GIT_TAG}"
		UPDATE_COMMAND ""
		CMAKE_ARGS ${DEP_CMAKE_ARGS}
		BUILD_BYPRODUCTS "${DEP_LIBRARY_PATH}"
	)

	add_library(${DEP_TARGET} STATIC IMPORTED GLOBAL)
	set_target_properties(${DEP_TARGET} PROPERTIES
		IMPORTED_LOCATION "${DEP_LIBRARY_PATH}"
		INTERFACE_INCLUDE_DIRECTORIES "${DEP_INCLUDE_PATH}"
	)
	add_dependencies(${DEP_TARGET} ${DEP_NAME}_external)

	set(${DEP_VAR}_INCLUDE_DIR "${DEP_INCLUDE_PATH}" PARENT_SCOPE)
	set(${DEP_VAR}_LIBRARY ${DEP_TARGET} PARENT_SCOPE)
	set(${DEP_VAR}_EXTERNAL_TARGET ${DEP_NAME}_external PARENT_SCOPE)
endfunction()
